name: Update Zinger Count

on:
  workflow_dispatch:  # Trigger manually with input for zinger count
    inputs:
      zinger_count:
        description: 'New Zinger Count'
        required: true
        default: '0'

jobs:
  update_counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update counter.json
        run: |
          echo "{\"zingers\": ${{ github.event.inputs.zinger_count }}}" > counter.json
          
      - name: Commit Changes
        run: |
          git config --global user.email "cooperdean06@gmail.com"
          git config --global user.name "comytt"
          git add counter.json
          git commit -m "Update zinger count to ${{ github.event.inputs.zinger_count }}"
          git push
        env:
          GITHUB_TOKEN: ${{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}}  # Use the secret token here
